### ISSUE TITLE
Uploading to Album in Design does not work for regular users

### ISSUE THREAD

**Issue by TakMarche** [projectfork/Projectfork#1313]
Been trying to figure this out for awhile now and I just can't seem to figure out what is wrong. Whenever I upload an image to an album as a regular user and set the "album" field to anything but the default "-Select An Album" the image won't upload and I get a "not allowed" error. If I give the user admin privileges it works just fine.. any reason why?

**Comment by eaxs** [comment]
Fixed in upcoming release.
