### ISSUE TITLE
BUG - Upload error in DragnDrop if file has more 30Mb...

### ISSUE THREAD

**Issue by maxgdias** [projectfork/Projectfork#1382]
Hello.'m With the following problem. 

1. If I drag and drop files larger than 30MB I get an error message in Google inspector 500 Internal Error. 

2. If I uploaded the individual file everything works correctly. 

I am the administrator of the server and can make any configuration changes. Currently my php.ini looks like this: 

register_globals = Off 
magic_quotes_gpc = Off 
session.save_path = "/ tmp" 
upload_max_filesize = 512M 
post_max_size = 512M 
max_input_time = 3000 
max_execution_time = 3000 
memory_limit = 512M 

Can you help me?
Thanks
Max

**Comment by eaxs** [comment]
So you're saying that you can't upload multiple files at the same time when the combined file size surpasses 30mb?

How many files are there? And please check the php error log for clues about that 500 error. This information should be very valuable.

**Comment by maxgdias** [comment]
Hi, thanks for replay.

No,
If i use drag and drop i cant upload one sigle file with 50MB
If i upload file in task using "chose file" the upload work with files
350MB....

Than, i think the problem was not in server configuration, but in the drag
and drop function...
Any idea?

Abraço,


2015-03-11 11:31 GMT-03:00 Tobias Kuhn <notifications@github.com>:

**Comment by eaxs** [comment]
The drag&drop handles uploads differently, and there are a lot of places where it could go wrong. Have you been able to see if anything is in the log file? That should point me in the right direction, as I can't reproduce it on my own.

**Comment by maxgdias** [comment]
In Joomla Log no error;
In Google Chrome console this error:

Failed to load resource: the server responded with a status of 500
(Internal Server Error)

http://www.estudiomx.com.br/index.php/index.php?option=com_pfrepo&task=fileform.save&filter_parent_id=14&format=json&qqfile=Max_156_90.jpg

In repo folder, the file was not there...

The processe i do was:
1. Login in frontend;
2. Select project;
3. Click in Upload files (my Disco Virtual)
4. Drag and drop the file with 50MB
5. After upload the bar was red and the file was not saved;

Thanks for attention.


Abraço,


2015-03-11 12:52 GMT-03:00 Tobias Kuhn <notifications@github.com>:

**Comment by eaxs** [comment]
> In Joomla Log no error;

I mean the __PHP__ error log :)

**Comment by maxgdias** [comment]
Ok, sorry.

This is the log for all task do yesterday befor print the screens and send
you:

201.37.99.169 - - [11/Mar/2015:13:03:13 -0300] "GET
/index.php/painel-de-controle/13-yougroup-grupo-imobiliario HTTP/1.1" 200
4931 "http://www.estudiomx.com.br/index.php/projects" "Mozilla/5.0 (Windows
NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115
Safari/537.36"
201.37.99.169 - - [11/Mar/2015:13:03:13 -0300] "GET
/index.php/painel-de-controle/index.php?option=com_pfcomments&view=comments&filter_context=com_pfprojects.project&filter_item_id=13&tmpl=component
HTTP/1.1" 200 2128 "
http://www.estudiomx.com.br/index.php/painel-de-controle/13-yougroup-grupo-imobiliario"
"Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/40.0.2214.115 Safari/537.36"
201.37.99.169 - - [11/Mar/2015:13:03:15 -0300] "GET
/index.php/disco-virtual HTTP/1.1" 200 4749 "
http://www.estudiomx.com.br/index.php/painel-de-controle/13-yougroup-grupo-imobiliario"
"Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/40.0.2214.115 Safari/537.36"
201.37.99.169 - - [11/Mar/2015:13:03:16 -0300] "GET
/media/com_projectfork/projectfork/css/ajax-upload.css HTTP/1.1" 200 136 "
http://www.estudiomx.com.br/index.php/disco-virtual" "Mozilla/5.0 (Windows
NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115
Safari/537.36"
201.37.99.169 - - [11/Mar/2015:13:03:16 -0300] "GET
/media/com_projectfork/projectfork/js/upload.js HTTP/1.1" 200 37532 "
http://www.estudiomx.com.br/index.php/disco-virtual" "Mozilla/5.0 (Windows
NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115
Safari/537.36"
201.37.99.169 - - [11/Mar/2015:13:03:34 -0300] "GET
/images/slider/slide-1.jpg?1426089812831 HTTP/1.1" 200 191564 "
http://www.estudiomx.com.br/" "Mozilla/5.0 (Windows NT 6.3; WOW64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36"
201.37.99.169 - - [11/Mar/2015:13:03:59 -0300] "GET
/images/slider/slide-5.jpg?1426089838826 HTTP/1.1" 200 151258 "
http://www.estudiomx.com.br/" "Mozilla/5.0 (Windows NT 6.3; WOW64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36"
201.37.99.169 - - [11/Mar/2015:13:03:30 -0300] "POST
/index.php/index.php?option=com_pfrepo&task=fileform.save&filter_parent_id=14&format=json&qqfile=Max_156_90.jpg
HTTP/1.1" 404 - "http://www.estudiomx.com.br/index.php/disco-virtual"
"Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/40.0.2214.115 Safari/537.36"

Abraço,


2015-03-12 8:48 GMT-03:00 Tobias Kuhn <notifications@github.com>:

**Comment by eaxs** [comment]
This is the apache access log, still not what I needed to see :)
Please do the following: Login to the backend of your site, then go to: 
System -> System Information -> PHP Information. 

On this tab, search for `error_log` - You can press CTRL+F to bring up the search in your browser. It should tell you where to find the log file. 

If it reads "no value", go look in the same directory where you previously found the access log, it will most likely be there somewhere. Or just ask your hosting company/check their docs.

Thanks!

**Comment by maxgdias** [comment]
10000 sorry.

I delete de php.ini in host diretocry and all its working now!!!
Thanks


Abraço,


2015-03-12 12:48 GMT-03:00 Tobias Kuhn <notifications@github.com>:

**Comment by eaxs** [comment]
Glad you figured it out then :)
