### ISSUE TITLE
Error Design Module

### ISSUE THREAD

**Issue by ercolano** [projectfork/Projectfork#1453]
We have installed projectfork under joomla version 3.3.6
we get the following error when try to upload a file in design module

Strict Standards: Declaration of PFtableAlbum::_getAssetParentId() should be compatible with JTable::_getAssetParentId(JTable $table = NULL, $id = NULL) in /htdocs/web/administrator/components/com_pfdesigns/tables/album.php on line 313 

Please let us know a possible solution

thanks in advance

**Comment by eaxs** [comment]
Fixed in upcoming release
