### ISSUE TITLE
Joomla - Project Fork 4.2.2 - When creating new project the following error is produced

### ISSUE THREAD

**Issue by jmilitis** [projectfork/Projectfork#1472]
SplFileInfo::__construct() expects parameter 1 to be string, array given
 
 
Joomla Version: 3.3.6 Stable
Projectfork Version: 4.2.2 Stable
PHP Version: 5.5.17

**Comment by polar69** [comment]
I also get the same error, I have googled the string and although other admins are having similar problems there doesn't seem to be a relevent fix

0 SplFileInfo::__construct() expects parameter 1 to be string, array given 


    Joomla Version: 3.3.6 Stable
    Projectfork Version: 4.2.2 Stable
    PHP Version: 5.3.29

Please help :) I was really looking forward to using ProjectFork

**Comment by hennysmafter** [comment]
It could be possible that all of you users are using a plugin called JHackGuard. If so, then try to disable it while working with projectfork. It solved for me the error. Afterwards just enable it back on.

**Comment by eaxs** [comment]
Thanks @hennysmafter . Projectfork makes no use of the SplFileInfo class. So it can't be Projectfork producing the error :)
