### ISSUE TITLE
Cb 2.0 plugin

### ISSUE THREAD

**Issue by gridfree** [projectfork/Projectfork#1502]
When will the pro plugin be updated to community builder 2.0.

**Comment by agerix** [comment]
Hello, this is a good question, when this plugin will be available please ?
Thx for answer

**Comment by angek** [comment]
CB 2 is still in beta and not recommended for live sites. Once it has reached stable I'm sure the plugin will be updated accordingly.

**Comment by gridfree** [comment]
cb 2.0.5 is out, it is not in beta....

**Comment by scree23** [comment]
I am supporting the question, actually I am using CB 2.0.5 official release and your project plugin is not functional .(plugin: Community - My Projects) - simply not working with this version

Any patch or any tips how to modify the plugin?

**Comment by agerix** [comment]
CB 2.0.9 is not a beta too : http://www.joomlapolis.com/news/18497-community-builder-209-and-3-more-releases
