### ISSUE TITLE
URGENT: Also having drill down in directories issue

### ISSUE THREAD

**Issue by corconsulting** [projectfork/Projectfork#1506]
I have reviewed previous posts on this issue and don't seem to be able to identify the problem. it was working until recently and now it just refreshes the main project page and does not go into the directories within the project. I am not able to identify a javascript error and if there is one i clearly and not resolving it. I could really use some help with this as the site is a government funded site and the resources are completely inaccessible to the client and it's service providers. They are quite concerned that their documents are not currently available and are anxious to see this resolved. Can you please contact me and i can provide login credentials to see the issue first hand.

**Comment by corconsulting** [comment]
attention Kyle Ledbetter - as per email. I can post the link to the site but the area with the repository requires a password. Since this is a live site i would prefer to share this information privately.
http://northernliteracy.ca/index.php?lang=en

**Comment by jaapie1** [comment]
I am having the exact same issue. For me its a fresh install of joomla and projectfork on ubuntu.
Joomla! 3.3.6 Stable, PHP 5.5.9, Apache/2.4.7, Database 5.5.41.

**Comment by eaxs** [comment]
The issue has been fixed in the dev branch. You can either wait for the next release (coming within this month), or you can carefully grab and install a copy of it as described here: https://github.com/projectfork/Projectfork/wiki/Downloading-the-code

**Comment by jaapie1** [comment]
Thanks guys, that was a very quick answer.
I'm going to install the dev branch.
Jasper

Tobias Kuhn wrote:

**Comment by jaapie1** [comment]
OK. I installed the dev branch. This is a fresh install of joomla, with only projectfork installed. I can create a directory (although it gives me the message "Error Save failed with the following error:" - it still creates it). If I create another directory next to this new directory and upload a file into this one, this file is shown also in the other directory. I know this is a dev branch so I know this is not a polished version, just wanted to give you a heads up.
