### ISSUE TITLE
Gantt Chart

### ISSUE THREAD

**Issue by promidgetmafia** [projectfork/Projectfork#1508]
I have purchased projectfork pro. However, "Gantt Chart" is not listed as an option to download under "My Collection" when I'm logged into the projectfork website.

In addition, where is the "AppTheme" template? 

Was this recently removed or does it need to be enabled on my account (Just purchased projectfork about an hour ago)

Thank you!

**Comment by kingface** [comment]
same over here. Gantt chart is very important to us!

Thanks.

**Comment by promidgetmafia** [comment]
Emailed them here: support@projectfork.net
and they responded the same day with the problem resolved.

Thank you
