### ISSUE TITLE
Created by: No author shown?! Possibly a bug.

### ISSUE THREAD

**Issue by FloryGlory** [projectfork/Projectfork#1513]
After creating a task, normally the name of the project and the author of the task should be shown. The name of the project is displayed but not the author.

I can't find the mistake. It is the 
COM_PROJECTFORK_FIELD_CREATED_BY_LABEL. Anybody else, who has the same problem? Is it a bug?

Please note my attached screenshot.
   Joomla Version: 3.3.3 Stable
    Projectfork Version: 4.2.2 Stable
    PHP Version: 5.3.29

![screenshot_projectfork](https://cloud.githubusercontent.com/assets/10502545/5707345/5f81d9c8-9a88-11e4-8b43-8d70d6f3522a.png)

**Comment by eaxs** [comment]
Could you check the html source and see if the author is present there? It could be that your template CSS is hiding the content by accident.

**Comment by FloryGlory** [comment]
eaxs, thank you. That's the point. For some unknown reason it was hidden by display:none in com_content.css. Sorry for opening this issue too fast. I Havent't seen the wood for the trees ;)

**Comment by eaxs** [comment]
Cool, glad I could help :)
