### ISSUE TITLE
Rename PF components in front-end possible?

### ISSUE THREAD

**Issue by cahecker** [projectfork/Projectfork#1518]
I am starting to use PF 4.2.2 Pro for a project with many contributors. To make it simpler for the contributors, I would like to adjust the display name of the components to the "system" that we use within that project, e.g., rename "Task" wherever it appears to "Activity". 
Is there a simple way to change the display name of a component in all locations in the frontend layout without diving into a lot of scripting?
tnx!

**Comment by cahecker** [comment]
i presume it could be done by making a custom language pack? are there instructions / guidelines of how to tackle that?

**Comment by eaxs** [comment]
You could use the Joomla language overrides as described here: 
https://docs.joomla.org/Language_Overrides_in_Joomla
