### ISSUE TITLE
Joomla Project Fork 4.2.2 Unable to create a new project

### ISSUE THREAD

**Issue by polar69** [projectfork/Projectfork#1519]
When I create a new project I get the error below, I have googled the string and although other admins are having similar problems there doesn't seem to be a relevant fix

0 SplFileInfo::__construct() expects parameter 1 to be string, array given

Joomla Version: 3.3.6 Stable
Projectfork Version: 4.2.2 Stable
PHP Version: 5.3.29

Hosted on Siteground

Please help :) I was really looking forward to using ProjectFork

**Comment by angek** [comment]
PF doesn't use SplFileInfo. have you installed any other Joomla plugins around the same time?

**Comment by polar69** [comment]
This is a new website so pretty much all my plugins are recent,does joomla keep an install log I could pick through maybe ?

Thank you for your help

**Comment by eaxs** [comment]
@polar69 Do you use an extension called JHackGuard? Someone recently reported that this extension was the source of the problem.
