### ISSUE TITLE
Labels on Task view

### ISSUE THREAD

**Issue by ingjjaa** [projectfork/Projectfork#1520]
I'd like to see the labels on the task view, i think that that would be easy changing the core but i'm no able to, would some one help me please 
![task edit](https://cloud.githubusercontent.com/assets/10730961/5927265/77c08b44-a643-11e4-955a-2614d53888af.jpg)
![Uploading task view.jpg . . .]()

**Comment by angek** [comment]
may I suggest you don't modify the core directly but instead create a template override for the task view.
I'll mark it as a feature request for future consideration. If you have an immediate need for this you'll have to reach out to a developer to code it for you.

**Comment by angek** [comment]
you're not talking about the task edit view are you? labels appear in a tasks edit view

**Comment by ingjjaa** [comment]
HI would you explain me how to make the override please.

In the Task edit view i can see the labels but I would like that the user that can't edit a task or super user that just want to read the description of a task could see the label asigned to that task, i really need it, would you help me please

**Comment by angek** [comment]
@ingjjaa please understand that at the moment we are trying to focus on getting through as many bugs as possible and time constraints mean that I cannot devote time to putting together a comprehensive tutorial on how to create this particular override.

You would be best served by paying a Joomla developer to do it for you.

Best of luck!
