### ISSUE TITLE
Problem whit email notifications!

### ISSUE THREAD

**Issue by mackedoon** [projectfork/Projectfork#1521]
Hello,

Afther I add a new task users asign receive email notiifcation.
The problem is when someone add a new comment, email notiifcation is send only to person how create the task.
Can someone help me?
All plugin are published.

**Comment by gauravdata** [comment]
I am also having the same issue, please provide the solution.

How should i resolve this ?

**Comment by mackedoon** [comment]
the users assinged to the task need to enable email notification from task details (frontpage) in the right corner it is a small icon that need to be green.
I don't know how this options it is not enable default.
hope to help you!

PS: Sorry for my english!
![untitled](https://cloud.githubusercontent.com/assets/10741063/5991458/5d2a8870-a9f9-11e4-919d-7353ad905f98.png)

**Comment by gauravdata** [comment]
Thanks a lot Mackedoon for this great support. I now got the mails on the comments. Can you please tell how i can set the notification to be enabled by default ?

**Comment by gauravdata** [comment]
Please also tell how could i get the notification of comments in User Activity ?

**Comment by angek** [comment]
the User Activity component does not provide notification. Im not sure why you would need User Activity notifications given that notifications from all the PF components are already enabled and working for you.

**Comment by gauravdata** [comment]
Angek, Comment on the any task is also the part of the User Activity if by any chance he missed the mail or he didn't check the mail, he must see the latest activity here. Like in the ProjectFork 3, Enclosing the screenshot.
![user activity](https://cloud.githubusercontent.com/assets/10793858/6097393/a717bc34-afe2-11e4-807c-971308f3d6a4.png)


Second, Auto-Enabled Email notification for projects and task is not active in my projectfork 4, please tell how do i make if default enabled for all the projects and tasks.

**Comment by eaxs** [comment]
Your users can subscribe to the entire project, instead of each task manually. To do this, everyone needs to click on the mail button next to the project, so that it's lit green: 
![sub](https://cloud.githubusercontent.com/assets/489521/6121896/9a81ad36-b0eb-11e4-8344-6ddc24b59bf9.jpg)

Regarding the user activity: it is indeed not recording comments. I'll have to add this feature.

**Comment by gauravdata** [comment]
@eaxs can this email notification button set to "on" for all the user and for all the new projects created ?

**Comment by eaxs** [comment]
With a little bit of code hacking, it should be possible. I have to look at it closely and see what needs to be done.
