### ISSUE TITLE
Milestones not showing duration in calendar

### ISSUE THREAD

**Issue by cahecker** [projectfork/Projectfork#1523]
even if the calendar option is set to show "duration" rather than just start or end date, milestones only show their end date.
of course we can argue whether milestones should have a duration (see issue #311 ) but since its currently often used as an overarching container for tasks, it should show with duration as well, i presume?
@kyleledbetter : any thoughts on what is going wrong?

**Comment by kyleledbetter** [comment]
I've somehow never noticed this, @eaxs what did you intend here?

**Comment by eaxs** [comment]
I'm unable to reproduce this issue. This could be a cache issue. Please setup your module the way you want it and then clear your joomla site cache. 

Let me know if that works.

**Comment by cahecker** [comment]
I have caching disabled in the global settings.

**Comment by eaxs** [comment]
Alright, then lets go a step further. Can you post some example data which allows me to reproduce this issue? I basically need a skeleton setup of your project, like this:

* Project A (start/end)
* Milestone A (start/end)
* Task A (start/end)

I have tried several different setups prior to writing this, and it always displays the duration correctly.

**Comment by cahecker** [comment]
Our pf site is life but not in use yet. Would it be easiest to give you a superuser login? If so, can you give me an email address to send it to?

**Comment by cahecker** [comment]
@eaxs  : 
I just tried it with a simple dummy project:
project <test calendar 2>; start 2015/1/31 end 2015/3/28 
milestone <workshop> under project <test calendar>; start 2015/3/16 end 2016/3/19
activity <give lectures 2> under project and milestone; start 2015/3/18 end 2015/3/19

activity is showing in calendar with duration
milestone is only showing end date

**Comment by eaxs** [comment]
Really strange. I setup a project like this and it seems to look alright:
![screen_calendar](https://cloud.githubusercontent.com/assets/489521/5988684/d707ab8a-a96a-11e4-851d-df654fb7bbee.jpg)

Config:
![screen_config](https://cloud.githubusercontent.com/assets/489521/5988693/f01d4e36-a96a-11e4-8ae7-996d24c30641.jpg)

It would probably best if I take a closer look at your site. Please send a super admin login to support@projectfork.net.

**Comment by cahecker** [comment]
Thanks for sending a screendump of the "option", @eaxs , makes me realize that there are 3 places in "options" to set to "duration" not just 2! :-/ it's working now exactly as intended and I apologize for wasting everyone's time.
