### ISSUE TITLE
Calendar projects and tasks always display a day early?

### ISSUE THREAD

**Issue by BrenDude** [projectfork/Projectfork#1524]
Hello,

I'm a recent ProjectFork Pro user. I just added the latest ProjectFork & Calendar to my site. My Calendar displays my projects and tasks; but they are all displaying on the calendar 1 day early. Not sure why? Please help. Thanks in advance. 
More info:
Joomla Version: 3.3.3 Stable
Projectfork Version: 4.2.2 Stable
PHP Version: 5.5.12

**Comment by BrenDude** [comment]
Friendly bump...

**Comment by angek** [comment]
what timezone have you set up in your Joomla config?

**Comment by BrenDude** [comment]
Hi angek.
In Joomla Global Config > Server tab > Server Time Zone = "New York".
Thanks in advance.
Also, what's going on with your awesome new gantt chart?  is it ready to purchase & download, yet?

**Comment by ingjjaa** [comment]
I need that some solve that problem one of the main feature of the pro has a terrible problem

**Comment by eaxs** [comment]
I'm closing this issue, as 2 patches have been released to fix the issue.
