### ISSUE TITLE
Currency settings should be at project level

### ISSUE THREAD

**Issue by devsaurin** [projectfork/Projectfork#1528]
Hi,

I feel currency level settings should be at project level considering scenario of multiple projects from multiple clients and currency. This will help to keep multiple projects with multiple currencies.

Thanks.

**Comment by angek** [comment]
agreed. Going to mark this as a feature request

**Comment by angek** [comment]
feature added to repo.

**Comment by devsaurin** [comment]
One suggestion... Why don't you close issues with commit message? It's better to check changes for each issue.
