### ISSUE TITLE
How to show TO WHO is assigned the task in front end?

### ISSUE THREAD

**Issue by dmware** [projectfork/Projectfork#1529]
My team is getting confused because when they view the projects' tasks they do not know what task is assigned to who.

Is there a way to show this label within the task view? Thanks

**Comment by eaxs** [comment]
I assume you mean the task overview list? 
You'll have to click on the little arrow icon next to the task, and then on "Details":
![task](https://cloud.githubusercontent.com/assets/489521/6064670/ead015d2-ad5f-11e4-8b1e-0ad85032dc06.jpg)

You can move this info somewhere else though. Take a look at the file `components/com_pftasks/views/tasks/tmpl/default.php`, around line 352 you should see:
```php
<?php echo JHtml::_('pftasks.assignedLabel', $item->id, $x, $item->users); ?>
```
You can cut this code and move it to appear somewhere else.

**Comment by dmware** [comment]
Thanks a lot eaxs. The problem was that I was not loading Bootstrap JS and so my template wasn't loading the dropdown arrows.

I tried to insert the line you mentioned within the single task page however it is working. If you have an easy way to implement it there too, it will be great.

By the way, if I have to purchase a custom dev service it's no problem. Thanks a lot and my compliment for this awesome tool.

**Comment by eaxs** [comment]
I've added it to the code base. You can Look at the changes made and apply it yourself, or make yourself an update package using the dev branch by following this guide: https://github.com/projectfork/Projectfork/wiki/Downloading-the-code
