### ISSUE TITLE
project for plugin forcommunity builder 2.0.5 stable been released

### ISSUE THREAD

**Issue by gridfree** [projectfork/Projectfork#1530]
project for plugin forcommunity builder 2.0.5 stable been released
the previous thread was closed without checking weather cb 2.0.5 has been releaed or not , i have purchased projectfork pro to use with cb 2.0,

**Comment by angek** [comment]
looks like I'm 2 weeks behind with my CB releases :)

**Comment by gridfree** [comment]
thanks for the update

**Comment by angek** [comment]
just updated my CB installation and successfully installed the current PF Projects plugin. While CB warns that the plugin is for the wrong CB version it'll work as expected. An update will be released in due course.

![cb_pf](https://cloud.githubusercontent.com/assets/1072484/6094539/16e2ab3e-af82-11e4-9446-b88922a2f07d.jpg)
