### ISSUE TITLE
Replace Document Author with Editor in Repository

### ISSUE THREAD

**Issue by mbsarino** [projectfork/Projectfork#1534]
@Angek: I have been trying to get the name of the editor to show in file revisions in the repository but I have thus far been able to work it out with @kyleledbetter .  Please see issue #1465.  Also, in the repository, I am not able to delete only 1 file from a group of revisions without deleting the entire group of documents  Is it possible to do this?  Please see issue #1493 

Thanks for your help!!

**Comment by angek** [comment]
@mbsarino to delete a specific file revision you will need to create overrides. The current code does not provide this functionality. I will mark this as a feature request and hopefully it'll make it into the core in the not too distant future.
In the meantime, if you have an urgent need for this functionality the only thing I can suggest is that you hire a Joomla developer to get it done for you.

**Comment by mbsarino** [comment]
@angek :  Thanks for the info.  I don't suppose I can hire your servicws? It is kinda difficult to find a Joomla developer who also is very familiar with PF4. As you know, it is due yesterday.  If you are available, please email me.  Thanks!!

**Comment by angek** [comment]
@mbsarino working on it ;)
will keep you posted.

**Comment by mbsarino** [comment]
Thanks for your help @angek!!

**Comment by mbsarino** [comment]
@Does this mean that if I download the latest dev, the "author-editor" issue is resolved?
