### ISSUE TITLE
ProjectFork filtering more than just names and categories

### ISSUE THREAD

**Issue by scree23** [projectfork/Projectfork#1535]
Hi, I would like to modify your Joomla extension a little bit. For our company purposes We need some more functions to filter the projects. Something like filtering the categories is just brilliant. We need something similiar for more database fields.

I would like to ask, if it is possible to add the function to filter the projects by Web adresses, e-mail adresses, telephone numbers and some of these additional database information I can add to project detail. These informations are already added in project details, but I can´t see any possibility to fiulter it. Is that possible? Can you explain me how to do it, eventually where to start. I can figure it out myself.

Thank you for reply.

**Comment by scree23** [comment]
And please can you provide me some advantages when I am buying the Pro version of Projetfork for 99 $? What are the main advantages? Thank you

**Comment by Solinfo** [comment]
humm...

Gant chart, calendar, template, and so on... But the major advantage is 
CONTRIBUTE salary of fantastic team! ;)

On 11/02/2015 7:26 AM, Jan Tykal wrote:
>
> And please can you provide me some advantages when I am buying the Pro 
> version of Projetfork for 99 $? What are the main advantages? Thank you
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/projectfork/Projectfork/issues/1535#issuecomment-73873306>.
>

-- 
Tout en restant Z, il est N* et Q et non pas Im de croire qu'il est C de comprendre en N la partie Q' de R!
(Traduction: Tout en restant relatif, il est naturel et rationnel et non pas imaginaire de croire qu'il est complexe de comprendre en entier la partie irrationnelle des réels!)

Normand Brousseau, B.Sc., M.Sc.
Solinfo enr.
Courriel: mailto:normandb@solinfo.ca
Pages web:
		http://www.solinfo.ca
	   	http://www.ambianceselecte.com


-----------------------------------------------------------------------

AVIS :
Ce message est confidentiel et à l'usage exclusif du destinataire. Toute autre personne est avisée qu'il lui est strictement interdit de le diffuser, distribuer ou reproduire. Si vous avez reçu ce message par erreur, veuillez nous en informer immédiatement par téléphone ou par courriel et effacer toute copie.

NOTICE:
This e-mail is confidential and intended for the exclusive use of the addressee. Any other person is strictly prohibited from disclosing, distributing or reproducing it. If you have received this e-mail by mistake, please notify us immediately by telephone or e-mail and delete all copies.

**Comment by angek** [comment]
@scree23 you can see the additional features that are available for Pro users at: https://projectfork.net/pro.html and like @Solinfo mentions it helps drive future development :)
As for additional filters it is not possible without modification to existing code. You'll need a developer to code it up for you.

**Comment by eaxs** [comment]
Filtering by the fields you've mentioned is going to be super expensive, performance wise. Because they are all stored in a TEXT field in json format. You can see it in the table pf_projects, field `attribs`.

If you really need it, I'd suggest catch the data upon saving/editing and offload or duplicate the data onto a new table which you can then use to build a more efficient query.

**Comment by scree23** [comment]
Hi, thanks for the informations. I´am gonna consider the official version, because We are building it for our company purposes and it will be neccessary to modify the extension a little bit.

It is possible to easily modify the search function in ProjectFork? Now it is searching just for titles of Projects, What if I need to filter the word in a content of Project, or some text in a detail page of project for example. It is possible to easily modify the search function to search wholle the content or it is too complicated to modify it as well?

Thank you for quick reply.

**Comment by eaxs** [comment]
It's not hard to modify at all. Take a look here: https://github.com/projectfork/Projectfork/blob/dev/source/components/com_pfprojects/site/models/projects.php#L239

```php
$filters['a'] = array('SEARCH', $this->getState('filter.search'));

// Apply Filter
PFQueryHelper::buildFilter($query, $filters);
```

Now you can either remove the first line and replace it with your own search query, or you can modify the `buildFilter` method here: https://github.com/projectfork/Projectfork/blob/dev/source/libraries/projectfork/database/query/helper.php#L49

If you change the buildFilter, it will likely affect all Projectfork search fields - not just projects.

**Comment by scree23** [comment]
I see Eaxs, that ´s well done and I am gonna implement it. 

But I still have my last question about the creator (user) of a project. Now it is clear to me, that creator is connected with Joomla user manager system and it is a human being who has created the specific project for first time. I figure it out, that I can change the creator manually in Joomla backend. I have installed some module, which can filter the creators of article by selecting them. It is similiar, the Projectfork projects and the articles in Joomla? Does they behave similiary? My goal is to have the possibility filter any projects by creator´s name (Joomla user name).

Thank you

Thank you for some tips, how to achive it .

**Comment by scree23** [comment]
Well, finally I get some time to resolve the search possibilities in ProjectFork and I want to thank you for your help. You gave me a good tip where to start. For the first time I thought I will have to develop some Smart Search plugin, but finally it was easy to modify the "buildFilter". It cost me less work and it does the same thing. My goal was to search not just titles of projects, but in description of project as well.

Sending you the modified buildFilter plugin, it should be usefull for someone:

case 'SEARCH':
                    if (!empty($value)) {
                        if (stripos($value, 'id:') === 0) {
                            $query->where($field . '.id = ' .(int) substr($value, 4));
                        }
                        elseif (stripos($value, 'author:') === 0) {
                            $value = $db->Quote('%' . $db->escape(trim(substr($value, 8)), true) . '%');
                            $query->where('(u.name LIKE ' . $value . ' OR u.username LIKE ' . $value . ')');
                        }
                        else {
                            $value = $db->Quote('%' . $db->escape($value, true) . '%');
                            $query->where('(' . $field . '.title LIKE ' . $value . ' OR ' . $field . '.description LIKE ' . $value .')');
                        }

PS: I just modified the ".alias LIKE" to ".description LIKE" (it is the field name in the database, you can change it for whatever field in database, table projectfork.

cheers
