### ISSUE TITLE
SEF links not CB 2.0 Compatible

### ISSUE THREAD

**Issue by nickanti** [projectfork/Projectfork#1536]
With CB 2.0.5 and Projectfork 4.2.2 on a Joomla 3.3.6 site.
If CB integration is enabled for User Profile link and User Profiel Avatar with Joomla SEF off, everything is working ok and the User links in the form of 

http://.../index.php?option=com_comprofiler&task=userProfile&user=680:user1&Itemid=111

works just fine.

But with SEF on this URL becomes:
http:/.../index.php/cb-profile/userprofile/680-user1
that gives a This profile does not exist or is no longer available ERROR

the SEF URL should look like:
http:/.../index.php/cb-profile/userprofile/user1

Actually it is best to use the CB 2.0 API function:
$_CB_framework->userProfileUrl( USER_ID_HERE )

to generate URL.

More about CB API here:
https://www.joomlapolis.com/support/tutorials/120-api-usage/18361-obtaining-field-values-through-getfields-api

**Comment by eaxs** [comment]
Hi Nick, 

Thanks for letting us know. I'll get it updated for the next release (coming out this month).
