### ISSUE TITLE
404 Error when updating projects after creating new tasks

### ISSUE THREAD

**Issue by madime** [projectfork/Projectfork#1537]
I'm hoping PF will work for what I need and am interested in getting the Pro version, but I can't get the free version to work. I'm constantly getting 404 Errors when using the backend for simple stuff. My versions are Joomla = 3.3.6; PF = 4.2.2; PHP = 5.3.28 (the tmp directory exists with what appear to be normal settings in php.ini and 755; however, a warning in extension manager says it's not set).

The error occurred after two types of situations; these only occurred in the backend (I couldn't even get so far as to do anything in the frontend yet):
1. I installed PF but failed to publish the module for the menu. I created a new project with basic info and successfully saved it. Then every time I went back into that project and then exited it (via Save, Save & Close, or just Close), it returned a 404 error.

2. I uninstalled PF and re-installed it. Then I followed the setup instructions to publish the menu module on all pages. I created a new project (added dates, labels, changed permissions, etc.) and found I could successfully update it without an error like in the  first issue above. However, I created a task for that project (which I can successfully update & save without an error) and when I returned to the project again to update it, then once again I got the error when I tried to exit the project (again, either through Save, Save & Close, or even just Close without making any changes at all). 

Each time, the project file shows it checked out. Whether I check it back in or not and try the updates, I continue to get the 404 errors.

Please help because I'm optimistic PF can work for my site, but I I can't go on with these unexpected 404 errors.  Thanks!

**Comment by eaxs** [comment]
Could you post a screenshot of that 404 page you're receiving? I don't think I've seen this problem before - especially in the backend. Maybe there's an issue with another extension. It's hard to tell without taking a direct look at the site. Thanks!

**Comment by madime** [comment]
Thanks. The 404 is kicking to my default 404 page I normally have on my site so it won't display anything meaningful about the error. It's the same page I use for 500 & 403 errors, but I tested it yesterday and excluded catching the 403 & 500 and found it was only triggering the 404 error. 

As for potential extension conflicts, I use K2 for a lot of my site (statstuff.com) with a template & menu driven by Shape5. I also use several others that aren't as widely prominent which include AcyMailing, Akeeba BU, Compare for K2, Mijoshop (ecommerce), RSFirewall, RSFormPro, SEO Glossary and Xmap. 

I spent hours yesterday looking for conflicts in the tables & records related to PF but couldn't find anything odd. I thought it may have been access related (although I was logged in as a superuser only doing this in the backend), but to be sure I played with adding Admin access to my account and the projects and it still throws the same error. I created more projects and related tasks and couldn't replicate the error on the new projects although the old ones still cause the error. 

I'd like to think it's fixed, but it's frustrating that since I don't know the cause, I can't prevent or fix it if it happens again. And I'm redesigning my site in hopes to significantly depend on PF (including upgrading to Pro), but I can't if it won't work for my simple testing.

Thanks so much for any help you can provide!

**Comment by madime** [comment]
OK, I think I have more useful info now. I disabled catching the 404 error and found it gave the info below. I wonder if it is due to K2 that I use for articles instead of Joomla's default articles?

The path it was attempting: http://statstuff.com/administrator/index.php?option=com_pfprojects&view=project&id=1

The text displayed:
jos-Error: Article not found

JApplicationCms -> execute() @ /home/www/statstuff.com/index.php:40
JApplicationSite -> doExecute() @ /home/www/statstuff.com/libraries/cms/application/cms.php:251
JApplicationSite -> dispatch() @ /home/www/statstuff.com/libraries/cms/application/site.php:237
JComponentHelper :: renderComponent() @ /home/www/statstuff.com/libraries/cms/application/site.php:191
JComponentHelper :: executeComponent() @ /home/www/statstuff.com/libraries/cms/component/helper.php:332
require_once() @ /home/www/statstuff.com/libraries/cms/component/helper.php:352
JControllerLegacy -> execute() @ /home/www/statstuff.com/components/com_content/content.php:16
ContentController -> display() @ /home/www/statstuff.com/libraries/legacy/controller/legacy.php:730
JControllerLegacy -> display() @ /home/www/statstuff.com/components/com_content/controller.php:79
ContentViewArticle -> display() @ /home/www/statstuff.com/libraries/legacy/controller/legacy.php:693
JViewLegacy -> get() @ /home/www/statstuff.com/components/com_content/views/article/view.html.php:44
ContentModelArticle -> getItem() @ /home/www/statstuff.com/libraries/legacy/view/legacy.php:398
JError :: raiseError() @ /home/www/statstuff.com/components/com_content/models/article.php:162
JError :: raise() @ /home/www/statstuff.com/libraries/legacy/error/error.php:253

**Comment by eaxs** [comment]
That's all very strange. The URL it's trying access is not valid. At least, I dont recall Projectfork having it like this. It's missing the `&layout=edit` parameter. Without it, you'd get a 500 - Default layout not found.

What's more, the call trace has no references to Projectfork at all. It's just straight up going to com_content. So it may be K2, or something else... something that's messing with the routing. I'd check the 3rd party system plugins and disable them for testing.

**Comment by madime** [comment]
Thanks but actually that URL is only when I'm already in the project and click any button to exit the project where I make any edits or not (like clicking Save, Save & Close, or Close).  So the "&layout=edit" parameter does display when I'm actually editing the project, but it's the saving and/or closure to return to the Projects view that triggers the error.

The odd thing is that it's not on every project. I created some more projects since then with tasks, milestones & tasks lists and even played around with the permissions, and they seem to work fine. So for the new projects they look OK with hopefully no problem (although I don't know what may trigger the same error for them in the future).

So I suspect it wouldn't be due to K2 or other plugins since it's not affecting all projects. What are the critical references required between the tables/fields that PF uses? For example, is there a foreign key that possibly got omitted just for those projects? Or, is there some kind of update and validation that occurs when closing a project from the backend edit view that could be triggering an error?

**Comment by eaxs** [comment]
If you *just* press  the __close__ button, then nothing out of the ordinary should happen really. But if you __save__ or __save&X__ , then there's a whole of stuff going on. Especially with projects.

Saving triggers all content plugins, and for projects it's going to create a physical folder for your repository. Perhaps RSFirewall doesn't like that. We've had issues firewall/security tools in the past. You'll have to white-list at least the projects and repository component.

I don't know why all of this would work after you've created X amount of items, and fail to save all previous. Could be a lot of things, but from what we know so far it seems to be a "general" problem. And I wouldn't count on it not occuring in the future until the culprit has been dealt with.

**Comment by madime** [comment]
Thanks. Yes, I think it initially started with saving an edited project, but then it occurs again any time I only close the project without making any edits. And I believe among the original changes I made when I first saved the projects that triggered the errors included changing some user groups in the permissions area. That's what makes me think the original save included some changes that caused a conflict in the relationship references for just those projects. Then any time I re-open that project, it re-calls the conflict even when doing a simple close.

The firewall is something I haven't considered. But again, after creating more projects since then, the errors haven't occurred for those new projects (yet). I'll try tweaking the firewall to see if that helps.

**Comment by madime** [comment]
I think I found the trigger but it's not fixed yet. It's caused when I edit a project and add more labels after already adding one or more labels of any type. So the key is that one or more labels were already saved to the project (it appropriately accepts many labels the first time). But when I go back to edit a project and try to add one or more labels to the existing set of labels, the error triggers. 

What is triggering this error after adding more labels to a project?  What values can I change in the MySQL tables/fields to fix the existing projects?

If it helps, I added all of the PF components as exceptions to my Firewall. I saw the new labels don't get added to the pf_labels table (only the originally saved ones get added successfully). And the pf_ref_labels table seems to appropriately list the labels I assigned to certain tasks.

**Comment by madime** [comment]
By the way, I just purchased the PF Pro version. Despite these recent errors, I'm liking what I'm seeing as potential for what I need it to do on my site. Worst case I can avoid adding more labels to a project, but I hope that's the only trigger for this. 

Again, I'd appreciate any further help you can provide on this.  Thanks!

**Comment by eaxs** [comment]
Cool, thanks for your support :)

> when I go back to edit a project and try to add one or more labels to the existing set of labels, the error triggers. 

I've set up a fresh install of Joomla and Projectfork. Went to create a project in the backend with a couple of labels. Then I edited it again to add more labels and saving it was no issue at all.

Can you reproduce this issue if you create a new project, or is this only the case for the old ones? You could backup the tables `pf_labels` and `pf_ref_labels` and then truncate them. This will remove all labels and label connections. Then try again saving/editing your projects.

I'd appreciate a step-by-step guide on how I can reproduce this issue, if you can find it.

**Comment by madime** [comment]
Thanks for trying to replicate it. Yes, it happens when I even create a new project. I tried creating several new projects using different label types (global, milestone, tasks or combinations of them) and in EVERY case it was the same thing. They could be saved without an issue when I first add any number or type of label the first time (even if it's a previously saved project where I added no labels before); but as soon as I try to add any kind of label in addition to the labels I previously saved, then the error occurs. Again, once that error is first triggered, the error continues to occur even if I just try to edit that project and close it without even editing or saving it in any way.

I backed up the table as advised and truncated them and you're right, it lets me go back to edit those projects and save, save & close, or just close without any error at all.  That's a huge relief knowing worst case I wouldn't lose the entire project!

So step-by-step, here's a simple way I can replicate the issue all in the backend:
-From the Projects area, I click the NEW button
-I add a Title and one Global Label (all other fields are left blank or default)
-I click the SAVE button; it confirms it successfully saved.
-While still in edit mode for the project, I click on Labels to view the labels, then click the ADD LABEL button and add a description for the label (It doesn't matter if it's for adding another Global label or adding a different label type)
-I click the SAVE button; it returns me to my default 404 error page

In case it matters, I tested this in both Chrome & Firefox and get the same errors.

**Comment by eaxs** [comment]
Thanks for the info. Unfortunately it didn't help as I can still save with no issues and the error log shows nothing. I think at this point it would be best if you send a super admin login to support@projectfork.net so I can take a direct look. 

Thanks!

**Comment by madime** [comment]
I set it up and sent a separate email with the access credentials.  Thanks again for the help!!
