### ISSUE TITLE
Default avatar for CB 2.0 integration broken

### ISSUE THREAD

**Issue by nickanti** [projectfork/Projectfork#1538]
CB 2.0 default avatars are now not language specific.
The default images are located in:
components/com_comprofiler/plugin/templates/default/images/avatar

See broken image attached.

I will follow-up with code proposal if you guide me to relevant source file.
![2015-02-18_10-35-06](https://cloud.githubusercontent.com/assets/1327092/6244366/54a09fc2-b75b-11e4-946a-d2829f0b7e16.jpg)

**Comment by eaxs** [comment]
Odd, it's working for me. But I upgraded from 1.9x. So I probably still have the leftovers. You can see the code for getting the avatar URL here:
https://github.com/projectfork/Projectfork/blob/dev/source/libraries/projectfork/html/avatar.php#L121

So I just change the default path? What's the best way to detect the current CB version installed?
Thanks!

**Comment by eaxs** [comment]
Should be working now in the dev branch
