### ISSUE TITLE
Problem with the calendar

### ISSUE THREAD

**Issue by ingjjaa** [projectfork/Projectfork#1541]
Hi i think that the problem with the calendar in projecfork pro es something that should be solved as soon as possible because it's something critical, do someone know how to solve it ???

**Comment by eaxs** [comment]
What exactly is the problem with the calendar? You haven't mentioned it.

**Comment by ingjjaa** [comment]
The calendar show the task one day before i mean is the start day es 24/02/2015 it show it 23/02/2015 how can i solve it ??

**Comment by ingjjaa** [comment]
Can someone say when that problem will be solve ????
