### ISSUE TITLE
Can I install the new version 4.2 together with old one 3.0 ?

### ISSUE THREAD

**Issue by mareluna73** [projectfork/Projectfork#1542]
In this way my users can take confidence with the new one without stopping the normal activity
Could be very important.
Please let me know. 
Thank You.

**Comment by eaxs** [comment]
You mean using Projectfork 3 alongside 4? Short answer: No.

Both use the same names for database tables, but with a different data structure. PF 3 and 4 may share the same name, but are very different, both technically and in use scope. I really doubt it would make a lot of sense to use them both.

I recommend you retire or wrap up the projects that you currently have in PF 3 and keep that as an archive on a sub-domain, and then move on to PF 4. But again, PF 4 is nothing like PF 3 was. So you should test out everything before making a final decision!
