### ISSUE TITLE
Is this joomla extension compatible with this template?

### ISSUE THREAD

**Issue by lspreciado** [projectfork/Projectfork#1543]
http://pixeldrops.net/viska/standard/index.php/blog

I need some help, I need a project manager with this template or something similar... if any one know something about it tell me...

Thanks!

**Comment by eaxs** [comment]
From what I can see, this template seems to use bootstrap CSS, which is exactly what you need to use Projectfork properly. But it's not uncommon (even with bootstrap) that templates need some slight changes or modifications to make everything look nice.

**Comment by lspreciado** [comment]
Ok, thank you for the answer! 
I have another question because I need it in spanish... can we change the language?

**Comment by eaxs** [comment]
Yes you can :)
