### ISSUE TITLE
Differentiating the origin of event: onContentAfterSave ?

### ISSUE THREAD

**Issue by HelgeSverre** [projectfork/Projectfork#1544]
I am writing a plugin for Projectfork that will create a set of configurable "standard directories" inside the file archive in pf_repo whenever a new project is created.

However there is a problem, the same event(onContentAfterSave) I use to determine if a project is created is triggered both when a project is created, and when a new folder is created within the repo/filearchive.

This causes the plugin in it's current state to always create the directories in new directories created by the user, this is problematic.

Is there any way to know the "origin" of the event as I want the event to ONLY fire off when a new project is created, not when a new directory(or anything else) is created.
```php
onContentAfterSave($context, &$table, $is_new)
```

The ```$context``` (not sure what it is actually meant to be called) in the code above is not reliable enough to rely on as it will have the same value(```com_pfrepo.directoryform```) for both creating a new project and a new directory,

The event is triggered on line #585 in this file:
[com_pfprojects/admin/models/project.php](https://github.com/projectfork/Projectfork/blob/dev/source/components/com_pfprojects/admin/models/project.php#L585)

Now, I could fix this by adding an additional field to the trigger in the model myself, but I wanted to see if there was a "proper" way to do this.

The plugin will be open sourced when it is done.

**Comment by eaxs** [comment]
The content plugins should get triggered twice when saving a project, but with different contexts. The project model calls upon the repo dir model to create the initial folder, which then triggers its own event. After that, the project model triggers the content event again for its own context.

So you have to check the context in your plugin before processing the data:

```php
public function onContentAfterSave($context, $table, $is_new = false)
{
    if ($context != "com_pfprojects.form" && $context != "com_pfprojects.project") {
        // Unsupported context. Do nothing...
        return true;
    }

    // Project context. Process data here...
    return true;
}
```

If I remember correctly, it is important to return `true` even when the context is not supported. Otherwise you're breaking the loop that calls the remaining plugins which may have wanted to process the data/event in this context.

**Comment by HelgeSverre** [comment]
First of all thanks for the quick answer, very appreciative.
Although I am still having troubles. 

This is the code I currently use, It still triggers when a user creates a new directory/folder in the file repo manually, am I missing or am i misunderstanding something?

```php
<?php defined('_JEXEC') or die;

jimport('joomla.plugin');

class plgSystemStdpromap extends JPlugin
{

    public function onContentAfterSave($context, &$table, $is_new)
    {

	 if (   $context == "com_pfrepo.directoryform" 
	     && $context != "com_pfprojects.form" 
	     && $context != "com_pfprojects.project") {
	    	
	    	// Code that creates folders here...
	
		}
        return true;
	}
}
```

**Comment by eaxs** [comment]
Ah now I get it :)
Yes, the context `com_pfrepo.directoryform` is also used when the user creates a new folder. So you want to be using the other two contexts `com_pfprojects.form` and `com_pfprojects.project` instead.

So it should look like this:
```php
<?php 
defined('_JEXEC') or die;

jimport('joomla.plugin');

class plgSystemStdpromap extends JPlugin
{
    public function onContentAfterSave($context, &$table, $is_new)
    {
         if ($context != "com_pfprojects.form" && $context != "com_pfprojects.project") {
            // NOT in context of project save form, so stop here.
            return true;
         }

         // The user just created a project. Your code here...
         return true;
    }
}
```

At this point, the project and the root directory have already been created and stored. So if you want to modify those, just fetch the data from `$table` or the database.

**Comment by HelgeSverre** [comment]
Awesome, my code now works, I will release it to the general public once It has been tested in production for awhile.

Much appreciated, thanks!
