### ISSUE TITLE
Component menu isn't there

### ISSUE THREAD

**Issue by jrnegronvidal1510** [projectfork/Projectfork#1546]
I installed the program and the menu is not showing the component menu. I'm using Joomla 3.4.

**Comment by jrnegronvidal1510** [comment]
I'm still having the same issue. I uninstalled and installed the extension again but nothing.

**Comment by jrnegronvidal1510** [comment]
I really like the extension but apparently no one there.  Are you still giving support? Anyone there? Does anyone read the post?

**Comment by angek** [comment]
When you installed the PF package you would have seen a message saying that a menu module had been created which needs to be enabled. Have you done this?

**Comment by jrnegronvidal1510** [comment]
Yes I did. I have the module running but in the component menu  I can't  see anything. When I use the menu  I cant add a new project.

José Rubén Negrón Vidal
iPhone

**Comment by jrnegronvidal1510** [comment]
Something new about this?. Looks that I'm not the only one.

**Comment by eaxs** [comment]
See #1545
