### ISSUE TITLE
EOF Joomlapraise

### ISSUE THREAD

**Issue by vaconiit** [projectfork/Projectfork#1550]
Tobias,

all Projectfork links still point to the (no more existing) Joomlapraise site.
Will there be another host for the files, demo and such?

**Comment by eaxs** [comment]
The site is meant to move to a new server and it reverted to some old DNS record for some reason. Sorry about the confusion. It should be back to normal soon :)

**Comment by vaconiit** [comment]
Kyle already answered my question via Twitter.  Good to know Projectfork is being maintained!  It would be a shame to see this one go.
