### ISSUE TITLE
Does PF need to be updated for Joomla3.4 I am on PF version 4.0.2

### ISSUE THREAD

**Issue by DiGwork** [projectfork/Projectfork#1551]
Hi I would like to update PF to the latest version as i have just updated joomla to 3.4.
I enabled the update sites for PF on the back end as they were off.
But I am having and issue on the Updater, see screenshot.

**Comment by DiGwork** [comment]
![selection_051](https://cloud.githubusercontent.com/assets/6685896/6443478/d0acbc10-c0ff-11e4-99e7-bc81683259bd.png)

**Comment by DiGwork** [comment]
![selection_052](https://cloud.githubusercontent.com/assets/6685896/6443512/07856822-c100-11e4-9d70-3b131d41a8ac.png)

**Comment by angek** [comment]
It'll all be back up and working soon. Tobias is making some changes at the moment.
