### ISSUE TITLE
Is the a way to print out a filtered list of tasks

### ISSUE THREAD

**Issue by DiGwork** [projectfork/Projectfork#1553]
Hi In the past Angek made a plugin upgrade to Milestone list to allow for printing (#1192). But I would now like to be able to print a list that has been filtered.

**Comment by eaxs** [comment]
This is one of the oldest feature requests ever, which ironically, I added myself. I'll have to check out what angek has been doing and add it to the core + adapt it to also work for tasks. There are a bunch of new features in the upcoming 4.3 release. Maybe we can squeeze this in too.

**Comment by DiGwork** [comment]
Yes as I have a bunch of lazy technophobes with my one client, who are either to lazy to open a browser or too intimidated! Either way they need to work from lists which I spoonfeed them by using  Screenshot to PDF. 
As tech support I spend far too much time doing tasks like this instead of just being able to teach one of the less intimidated users how to press print button and print it for their less tech savvy team mates.

**Comment by DiGwork** [comment]
I also wish there was some way to dumb down the resulting info into reports for the Managers who are even more technophobic than their staff. For now I end up generating spreadsheets for them once again something don't I get paid to do but unless the Project management system does somehow magically deliver what they need, in the format they want it, I loose a client..

**Comment by angek** [comment]
have just committed changes to add print button to the following list views: forum, milestones, projects, repo, tasks, time and users.

**Comment by DiGwork** [comment]
as always Thanks Angek, When do you think it will be available to use?
