### ISSUE TITLE
Warning when attempting to download latest version

### ISSUE THREAD

**Issue by DiGwork** [projectfork/Projectfork#1554]
Hi I receive a warning notice when I use the link to download the latest version of PF from Github repository: https://projectfork.net/downloads/projectfork-4/projectfork-4-4-0-0

**Comment by eaxs** [comment]
The site is currently unavailable. I hope the issue will be resolved soon. But you can still download PF through github: https://github.com/projectfork/Projectfork/releases

**Comment by DiGwork** [comment]
Hi eaxs thanks for feedback. 
Do you know if there are any major plugin updates that make it worthwhile doing the PF4.2.2 update, and if there are any potential problems I must prepare for if I do that update. 

Should I rather wait for 4.4.0 as the link provided only has up to PF4.2.2
(I am not sure which version I am presently on. I just know it is PF4. Is there any way to check?)

**Comment by eaxs** [comment]
4.2.2 is the latest release. I think the URL is a bit confusing to read. What it means is Projectfork 4 - Version 4, but it looks like Projectfork 4.4 - which doesn't exist.

**Comment by DiGwork** [comment]
How do I see which version of PF4 I am on?

**Comment by eaxs** [comment]
Joomla Backend -> Components -> Projectfork

![screen_pf 4 - dev j3 - administration - dashboard_13_46_52](https://cloud.githubusercontent.com/assets/489521/6483753/f08bb9ca-c274-11e4-9487-48ed591dd4f5.jpg)

**Comment by DiGwork** [comment]
Cool thanks I am already on 4.2.2
Any idea when an update is going to happen that will include some of the new feature upgrades like print and export etc.

**Comment by eaxs** [comment]
I dont have an exact ETA just yet. Probably next week though - assuming the website gets back online asap.

**Comment by DiGwork** [comment]
cool thanks for the feedback eaxs! ;)

**Comment by BenoitGD** [comment]
Hi,

Just read the comments, thx EAXS for the update, I was scared PF would close.

In the meaning, is there a place I can dwl le Pro extensions for PF?

I haven't used PF in a while, but I remember some extra template and a calendar module I could dlw since I was a Pro customer. Am I right?

Are those things still available? Do I need for the website to come back up?

Cheers and thx for your time!

B.

**Comment by eaxs** [comment]
@BenoitGD please email tobias@pixelpraise.com and I'll send you the pro extensions :)
