### ISSUE TITLE
Projectfork Component does not appear in backend menu

### ISSUE THREAD

**Issue by BenoitGD** [projectfork/Projectfork#1557]
Hi,

I just installed Projectfork using the Github repository and tho the component did installed successfully, it does not appear under the Component Backend Menu.

To access the backend dashboard of PF I need to type in /administrator/index.php?option=com_projectfork.

I also tried to go under Extensions and try to "discover" the component, but joomla could not find anything not correctly installed.

Anyone as an idea why the component would not appear in the backend menu?

Let me know, and thank you in advance!

B.

**Comment by eaxs** [comment]
There seems to be an issue with new installs on Joomla 3.4. I assume that's where you installed it, right?

**Comment by BenoitGD** [comment]
Hi! Yes indeed, I installed it on Joomla 3.4! Anyway you know of fixing it? Thanks! :)

**Comment by eaxs** [comment]
I don't have a bugfix for it just yet. It's something with how Projectfork registers the menu items. It needs to be updated to support Joomla 3.4 properly, though I have yet to figure out where and why it's going wrong.

**Comment by BenoitGD** [comment]
Ok, it's not a big deal, I'll wait for an update! I can access it using the url!

**Comment by eaxs** [comment]
See #1546
