### ISSUE TITLE
Email notifications 

### ISSUE THREAD

**Issue by franzonal** [projectfork/Projectfork#1560]
Hi!
Can't get email notifications to work. I've activated plugin (set to "send direct"), and submitted user to notifications. Nothing seems to trigger email function. I'm using php mail function and joomla itself is sending out emails. What might be wrong here? Some advice would be very much appreciated!

**Comment by eaxs** [comment]
Your users must be "watching" the specific item. Otherwise they won't receive an email. You can read more about it here: https://projectfork.net/docs/15-basics/79-email-notifications

**Comment by ibweb** [comment]
Again, the person who is ASSIGNED the task needs to be auto subscribed to the task by default.  It makes sense that someone who is to fulfill the task should be autosubscribed to any updates.

The current settings only make the task creator auto subscribed.  

I, and several others, have been asking for this change to the notifications system for over a year.  Any chance this can be updated?

**Comment by eaxs** [comment]
Added :)

**Comment by franzonal** [comment]
Thanks, emails where blocked as spam.

**Comment by ibweb** [comment]
Thanks @eaxs, the latest dev version with your change fixed the issue!
