### ISSUE TITLE
Email notification

### ISSUE THREAD

**Issue by ingjjaa** [projectfork/Projectfork#1561]
HI is there any way to allow just one user level to subscribe to email notification, i mean register user don't be allow to subscribe but administrator user can do it

**Comment by eaxs** [comment]
If a user can see something, he can also subscribe to it. I suppose it would make sense that if the button visibilty would depend on the access level of the notification plugin, which is currently not the case.

**Comment by eaxs** [comment]
I've just added this feature. You'll see it in the next release :)

**Comment by ingjjaa** [comment]
Hi thanks when will be us be able to download that version ???

**Comment by eaxs** [comment]
Probably next week, but if you need it right now, you can follow this guide (use the `dev` branch):
https://github.com/projectfork/Projectfork/wiki/Downloading-the-code
