### ISSUE TITLE
Project details - input fields conditions (email / web)

### ISSUE THREAD

**Issue by scree23** [projectfork/Projectfork#1563]
Hello, I would like to edit the input fileds from project detail (which I actually edit from the Joomla backend). For example one input field normally used for email adress, I would like to use for project evidence number. The problem is that these input fields has some special conditions, that I have to use aerobase for email and system always check it. If the input field has no aerobase, than validation do not take it as an e-mail adress and the filed left empty. Can I find some Javascript who handle these conditions? Can I simply erase this condition to check the email adress and the same for website as I can use whatever inside the input field? (numbers, letters, without aerobase)

Thank you for any help.

**Comment by eaxs** [comment]
You can remove the validation without coding. Take a look a the file https://github.com/projectfork/Projectfork/blob/dev/source/components/com_pfprojects/admin/models/forms/project.xml#L101 which is located at `/administrator/components/com_pfprojects/models/forms` on your website. 

Notice the website field with the attribute `filter="url"`. You can remove this part, and also the filter for the email field below.

**Comment by scree23** [comment]
Hi Eaxs, thank for your response, I have already find that file and I think so, that these filter will manage the input fields rules. But even I completely deleted those filters from the XML file, nothing change.

Even without these filter tags, I cannot write just the numbers inside the email field. Because when I save it, the field in the detail left empty. I have to put the aerobase and than it saves the data.

So do you know which function exactly require the aerobase in that field? With website is it OK now, I need to change just the email field to take any text or number content.

Thank you for any tip you have.

**Comment by eaxs** [comment]
You're right. Seems I'm double checking the data format just before saving it, here: https://github.com/projectfork/Projectfork/blob/dev/source/components/com_pfprojects/admin/tables/project.php#L182

You can remove the following code:
```php
$website = $registry->get('website');
$email   = $registry->get('email');

// Validate website
if ((strlen($website) > 0)
    && (stripos($website, 'http://') === false)
    && (stripos($website, 'https://') === false)
    && (stripos($website, 'ftp://') === false))
{
    $registry->set('website', 'http://' . $website);
}

// Validate contact email
if (!JMailHelper::isEmailAddress($email)) $registry->set('email', '');
```

**Comment by scree23** [comment]
Aaaah that´s it. Thank you man, I seek that function for years and couldn´t find it. Now it is OK.

**Comment by bokigto** [comment]
scree23 can you detail your modifications a bit more. I would want to the same thing.

**Comment by scree23** [comment]
Hi Bokigto, what do you want to know exactly? I think that Eaxs just explain it pretty much. Those 2 fields has set the condition to accept only e-mail or website format. If you want to modify that field as in my case (i am using email adress field as project number), all you have to do is to modify two files:

 /administrator/components/com_pfprojects/models/forms/project.xml
> just delete the filters tags (filter="url" and filter="email")

 /administrator/components/com_pfprojects/tables/project.php
> comment all the condiitions as Eaxs marked before

That´s it. If you have some other problem try me ..

**Comment by bokigto** [comment]
thanks it's clear now.
