### ISSUE TITLE
Saving of priority/user... in frontend not working -> latest dev branch

### ISSUE THREAD

**Issue by enzo01** [projectfork/Projectfork#1570]
Hi,

While using the alternativ tasks view of the dev branch:

components/com_pftasks/views/tasks/tmpl/quantility.php
 
Saving of priority, add user etc. isn't working.
Using the normal view everthing is fine fine
 

Can someone confitrm this issue or is it just me ?

cheers
enzo

**Comment by eaxs** [comment]
I don't think this layout ever existed. Are you sure it was in the dev branch? https://github.com/projectfork/Projectfork/tree/dev/source/components/com_pftasks/site/views/tasks/tmpl

**Comment by enzo01** [comment]
Well right...
I guess I got it from a different fork...
I try to figure that out

**Comment by eaxs** [comment]
I'll close the issue then.
