### ISSUE TITLE
Community Builder 2.0.7 Profil links

### ISSUE THREAD

**Issue by patfrat** [projectfork/Projectfork#1572]
Hello

I got some problems with Project Fork and CB 2.0.7

My configuration is : 
Joomla Version: 3.4.0 Stable
Projectfork Version: 4.2.2 Stable
PHP Version: 5.5.22

When i choose to link profil to CB in Project fork configuration options, nothing is working.
Bad links !
Profil link points to /cb-moderate-user-approvals/userprofile/1234 instead of /cb-profile/userprofile/1234

Is it normal a Project Fork issue or a CB issue ?

thanks in advance !

**Comment by eaxs** [comment]
Support for CB 2 is coming in our next release. If you dont want to wait, you can get the current dev code from here: https://github.com/projectfork/Projectfork/wiki/Downloading-the-code

**Comment by patfrat** [comment]
thank you !
I will try it !

**Comment by patfrat** [comment]
Great ! It works like a charm ! thank you !
