### ISSUE TITLE
Edit Time in Front End

### ISSUE THREAD

**Issue by bimsrv** [projectfork/Projectfork#1577]
How do I edit time in frontend? The drop down next to the task shows "Edit" option but does not allow editing.

**Comment by eaxs** [comment]
Hey, could you clarify "does not allow editing"? Do you get a system message, or what happens when you click that button?

Thanks!

**Comment by bimsrv** [comment]
That issue is resolved now. It a problem with the editor.ThanksAshit                                                                                                                                                                                                                                                                                                                                        Ashit Goyal CEOBimsrv P *911141077818M +919810102556BBM 2AB79987                                                                                                                                                                                                                From: Tobias KuhnSent: Monday 27 April 2015 7:41 PMTo: projectfork/ProjectforkReply To: projectfork/ProjectforkCc: bimsrvSubject: Re: [Projectfork] Edit Time in Front End (#1577)Hey, could you clarify "does not allow editing"? Do you get a system message, or what happens when you click that button?

Thanks!

—Reply to this email directly or view it on GitHub.
