### ISSUE TITLE
Not enough data to render Gantt chart

### ISSUE THREAD

**Issue by jablfaran** [projectfork/Projectfork#1579]
I install projectfork ganttchart module. When I click dashboard menu  in front end display, the message show "Not enough data to render Gantt chart" below Projectfork Gantt. 

Any solution for this problem?

Thanks

Iqbal

**Comment by eaxs** [comment]
This typically happens if you no start and end dates set for your projects, milestones and tasks. The chart needs find a start and end date for the project.

**Comment by jablfaran** [comment]
Thank you for the answer and give me the solutions. 
----- Original Message -----
