### ISSUE TITLE
Sorting disabled. Select a project to enable manual sorting

### ISSUE THREAD

**Issue by jablfaran** [projectfork/Projectfork#1582]
Hello Eaxs, 
When I want to order Tasks, I cannot hold and drag the task to place I wan't. The message "Sorting disabled. Select a project to enable manual sorting" show below the Tasks. 
How to change the message in order  sorting enabled?

Thanks  for the support

**Comment by eaxs** [comment]
You just have to do what the message says :) You select a project by using the drop down list at the top of the page:
![screen_tasks_13_03_01](https://cloud.githubusercontent.com/assets/489521/7021891/96483cbe-dd26-11e4-9aeb-00d4402e8982.jpg)

After this, you should be able to drag tasks around.

**Comment by jablfaran** [comment]
Thanks Eaxs
I did select the project as you said. The message shows "sorting enabled. ..." but I still can't hold and drag it. What's problems?

**Comment by eaxs** [comment]
Sounds like a javascript conflict, most likely with the template. Go to the joomla backend, then: Components -> Projectfork -> Options (Button at top-right) -> Integration.

Start by setting "Load Bootstrap JS" to No. If that doesn't work, set "Load jQuery - Site" to No as well.
If none of these work, email me at support@projectfork.net with a login to your site so I can take a look.

**Comment by eaxs** [comment]
Fixed. Issue was caused by "YT Framework" system plugin.
