### ISSUE TITLE
Cannot edit project with numeric title

### ISSUE THREAD

**Issue by milosmojzis** [projectfork/Projectfork#1584]
If the first character of the project title is numeric, the created project cannot be edited. The URL for project update looks like this:

/projects?task=form.edit&id=28:222

and leads to HTTP 404 because the correct URL is the following:

/index.php/projects?task=form.edit&id=28:222

**Comment by eaxs** [comment]
Issue confirmed. You can temporarily fix it by setting the Joomla Global config option "Use URL Rewriting" to "Yes". But remember to also rename your "htaccess.txt" file to ".htaccess" in your joomla installation directory.
