### ISSUE TITLE
CHANGELOG OF 4.3.1

### ISSUE THREAD

**Issue by mbsarino** [projectfork/Projectfork#1585]
Hello everyone!  Where can I find the changelog for v. 4.3.1?  I'm wondering if my problem with the previous versions of PF4 were addressed in the latest release.  This is the issue where versioned documents in the repository don't reflect the name of the document editor but rather the original author/uploader of the document.

Any info on this is appreciated!!

**Comment by eaxs** [comment]
The changelog for 4.3.0 can be found here:
https://projectfork.net/blog/13-releases/92-projectfork-4-3-released

And the changes for 4.3.1 is:
> Fixed:
Error when trying to create a new repo directory
Error when trying to delete a repo directory

Can you point me to your issue on github again?

**Comment by mbsarino** [comment]
Hi @eaxs 

Thanks for the changelog link! Please refer to #1534 and #1465 on my issues with the repository.

**Comment by eaxs** [comment]
I just pushed a fix for it. Unfortunately the user id of the uploader was never changed. It always used the user id of the original file/note. So the information for existing items is unrecoverable :(

**Comment by mbsarino** [comment]
Thanks for the explanation and initiating a fix for it!!

**Comment by eaxs** [comment]
You're welcome!
