### ISSUE TITLE
Alert message about the active project in project detail -disable

### ISSUE THREAD

**Issue by scree23** [projectfork/Projectfork#1588]
Hello, please I have a problem with alert message shown up everytime I open some project for first time. I would like to disable it, but it is called but some javascript, I cannot find it.

One time I disabled it, it takes me some time to figure it out, but after update to the latest version of ProjectFork, this message shows again.

I now it takes me some time to disable it, so maybe you could give me a little advice where I can find it and the rest I take care.

Only thing I know it is this text label: COM_PROJECTFORK_INFO_NEW_ACTIVE_PROJECT

Thank you for help.

**Comment by eaxs** [comment]
Looks like there's a missing translation. Which language package are you using?

**Comment by scree23** [comment]
Ohhh man I already find it. Translation is good, it is just the massage about the active project which bothered me, but I made it disappear.

The alert message is defined here: libraries/projectfork/application/helper.php
about line 220 you have to comment those conditions to generate the active company message.

Thank you
