### ISSUE TITLE
Only show projects of one category

### ISSUE THREAD

**Issue by SusanScotch** [projectfork/Projectfork#1589]
Hello!

I love your component. Only one question: Is there any chance to have a menu link directly to all the projects of a single category? This way the user does not have to use the filter...

Thanks!

Susan

**Comment by eaxs** [comment]
Hi Susan,

You can create a menu link (Type: System Link -> External):
![syslink](https://cloud.githubusercontent.com/assets/489521/7181446/1cf8e3d2-e44b-11e4-82f9-43310ef98c9b.jpg)
pointing to:
`index.php?option=com_pfprojects&view=projects&filter_category=x`, where the `x` at the end is category id. 
You can see the category id's by going to: 
Backend -> Components -> Projectfork -> Projects -> Categories
![cats](https://cloud.githubusercontent.com/assets/489521/7181477/53fb1814-e44b-11e4-90de-a464ee5a0692.jpg)

**Comment by SusanScotch** [comment]
Thank you very much! Great!
