### ISSUE TITLE
Link Task with files

### ISSUE THREAD

**Issue by jordiascension** [projectfork/Projectfork#1591]
Hello, Is it possible to link one task with one file?. I can see files linked to a project, but I cannot see files linked to a task. Thank you

**Comment by eaxs** [comment]
Yes it's possible. 
When you create or edit a task, look for the "Attachments" tab. That's where you can upload new files and __select__ them to become attached to the task.

**Comment by jordiascension** [comment]
Yes I did it in this way, but after I edit the attachment and save the task, I cannot see them in attachment tab.

**Comment by eaxs** [comment]
Hmm, maybe you can explain step by step what you are doing, so I can reproduce the issue.

Here's what I do:
* Go to Tasks -> New Task -> Attachments tab
* Click "Select Attachment" button and use the highlighted buttons to select the files I want:
![attach](https://cloud.githubusercontent.com/assets/489521/7319475/2ea34f9a-ea96-11e4-9a9a-bfb71bb15f6c.jpg)
* Then the tab looks like this when I'm done:

![attach2](https://cloud.githubusercontent.com/assets/489521/7319514/816b73d8-ea96-11e4-8753-112e31086997.jpg)

**Comment by jordiascension** [comment]
When I go to select attachment, I cannot select them or delete them but I can upload new ones. I show you a print screen:

![captura de pantalla 2015-04-24 a las 19 56 41](https://cloud.githubusercontent.com/assets/3955758/7325674/357f36a6-eac0-11e4-9fb8-272ead8e01c4.png)

**Comment by eaxs** [comment]
Are you using Joomla 2.5? It seems that the bootstrap CSS is missing, causing the buttons not to appear even though they exist. This is how it should look like on Joomla 2.5:

![screen_tasks_15_22_06](https://cloud.githubusercontent.com/assets/489521/7348362/379953da-ecf1-11e4-8d17-9b4232def9d6.jpg)

Please go to: Backend -> Components -> Projectfork -> Options (Top Right) -> Integration. 
Set `Load Bootstrap CSS` to "Yes" and check if that works.

**Comment by jordiascension** [comment]
Yes, you're right, it is working perfectly. Thank you for your help!!
