### ISSUE TITLE
Filtering projects by the "Deadline" - customizing the project main overview

### ISSUE THREAD

**Issue by scree23** [projectfork/Projectfork#1594]
Hello,

Maybe my question was not clear enough, so I try to explain my mission again.

I do not need the deadline field for projects and I would like to customize it a little bit. I would like to use deadline as date of creation for every project, because it is the only date I need and it is very easy to filter the deadline date without changing this function.

Everything is setup and functional, but only problem I have is how the deadline date is shown in project overview.

I would like to see the normal date in format as (D.M.Y). but in project overview I see only how many days left to deadline date. When I do the mouseover, I can see the date in strange format (just month and year).

Could you please help me, when I can find this function, which shows the days left to deadline and how can I cahnge it to show me clear date in classic PHP format, as a fixed date.

Thank you for any tips, where to find it. I look into default.php in com_pfprojects, but I did not find it.

Printscreen is in my last post.

**Comment by eaxs** [comment]
If I understand you correctly, you just want to change the default order in which projects are displayed?
To change it in the frontend, take a look a the project model here: https://github.com/projectfork/Projectfork/blob/dev/source/components/com_pfprojects/site/models/projects.php#L260

Change:
```php
protected function populateState($ordering = 'category_title, a.title', $direction = 'ASC')
```
To:
```php
protected function populateState($ordering = 'a.created', $direction = 'ASC')
```

Next, you want to add a new option to the select list in the filter, here: https://github.com/projectfork/Projectfork/blob/dev/source/components/com_pfprojects/site/views/projects/view.html.php#L194

Add a new option to the other ones:
```php
$options[] = JHtml::_('select.option', 'a.created', 'Creation Date');
```

And that's it :)

**Comment by scree23** [comment]
I would like to more edit the "deadline" field in main project overview. I would like that field show me the exact date and not the countdown number to deadline. To fully understand my problem, I am adding the printscreen of what the field showing me now.

Is there the possibility to change the value of this filed to show me the deadline date as follow: 01.01.2011 (something like that) ?
The filtering I just figure out, thank youf for help.

![ps555](https://cloud.githubusercontent.com/assets/10220621/7388236/ff7a64a2-ee63-11e4-93f6-6166a93876a8.png)
