### ISSUE TITLE
User Activity Compnent not in Component Menu

### ISSUE THREAD

**Issue by charlessteiner** [projectfork/Projectfork#1601]
Howdy! 

I've tried to install pkg_useractivity_1.2.2.zip on two J! 3.4.1 installations (same server). No joy

There is no User Activity in Components >.  

Module is showing on front end.
It is  listed in extensions > manage and is enabled. I'm logged in as superU. 

Any ideas? I feel I'm overlooking something simple, but I can't put my finger on it

Following instructions on: http://projectfork.net/docs/23-user-activity/46-installation (FYI, on that doc page, you might want to update the names of downloads, they are listed as PF plugin and PF Module -- not UA)

    Joomla Version: 3.4.1 Stable
    Projectfork Version: 4.3.1 Stable
    PHP Version: 5.4.40

![screenshot from 2015-05-04 11 12 26](https://cloud.githubusercontent.com/assets/2821240/7457035/1a353184-f24f-11e4-9373-0cc32dfdd407.png)

![screenshot from 2015-05-04 11 18 35](https://cloud.githubusercontent.com/assets/2821240/7457075/5f0e8d46-f24f-11e4-9978-28ed2ae8372e.png)

**Comment by eaxs** [comment]
Hey thanks for letting me know about this. I've just made a new release that should fix the issue.

> FYI, on that doc page, you might want to update the names of downloads, they are listed as PF plugin and PF Module -- not UA

While they are UA modules, these are tailor made for Projectfork. Hence I use the PF prefix :)
I'll close this issue as the latest patch should have fixed it. If not, please re-open it or make a new one.

Thanks!
