### ISSUE TITLE
Loading and using Select2 in com_pfprojects

### ISSUE THREAD

**Issue by HelgeSverre** [projectfork/Projectfork#1603]
I am trying to add functionality "assign user"-type functionlity to pfprojects the same way it is done in pftasks, so I have added this line:

```xml
<field name="users" type="userref" multiple="true" label="COM_PROJECTFORK_FIELD_REFUSER_LABEL" description="COM_PROJECTFORK_FIELD_REFUSER_TASK_DESC"/>
```
to the **administrator/components/com_pfprojects/models/forms/project.xml** file 

Then load it in the **components/com_pfprojects/views/form/tmpl/edit.php** file like so:

```xml
<?php echo JHtml::_('tabs.panel', JText::_('COM_PROJECTFORK_FIELDSET_ASSIGNED_USERS'), 'projects-users') ;?>
    <fieldset>
        <div id="jform_users_element" class="formelm control-group">
            <div id="jform_users_reload">
                <?php echo $this->form->getLabel('users'); ?>
                <?php echo $this->form->getInput('users'); ?>
            </div>
        </div>
    </fieldset>
```

But when I try to load the create project form in joomla It tells me that jQuery.select2() is not a function:

```
Uncaught TypeError: jQuery(...).select2 is not a function
```

I however cannot see where pftasks might be "preloading" it in, and adding it manually via JDocument->addscript and addstylesheet does not seem to work.

Have I missed something?

I realise this is not directly a projectfork bug or anything, but the dev team's insight would be highly appreciated.

**Comment by HelgeSverre** [comment]
Never mind

I fixed it by adding this at the BOTTOM of this file: **\components\com_pfprojects\views\form\tmpl\edit.php **


```

<?php
$doc = JFactory::getDocument();
$doc->addScript("/media/com_projectfork/select2/js/select2.min.js");
$doc->addStyleSheet("/media/com_projectfork/select2/css/select2.css");
```

**Comment by eaxs** [comment]
Yep that works :)
