### ISSUE TITLE
Show date instead the deadline countdown in project overview

### ISSUE THREAD

**Issue by scree23** [projectfork/Projectfork#1604]
I would like to show a normal date format in project overview and not the countdown to deadline. I cannot find that function which handle this field. When I roll the mouse over it, I can see the date I want as a ToolTip. I would like to use this normal date format to be shown in overview. Look to my image attachment to clearify my question.

I would like to show the date in follow format: 01.01.2011
 
Thank you for tips where I can find the file, Javascript or something which handle the date format and the countdown text in project overview.

![ps4](https://cloud.githubusercontent.com/assets/10220621/7493653/0621a104-f403-11e4-9f13-ad2e58bdecd2.png)
.

**Comment by HelgeSverre** [comment]
The HTML for those date fields are defined in this file:
``` https://github.com/projectfork/Projectfork/blob/dev/source/libraries/projectfork/html/label.php ```

Which most likely is located in this directory on your website:
``` libraries/projectfork/html/label.php ```

What you could do to simply get the date formatted as dd.mm.yyyy is this:

go into this file:
``` components/com_pfprojects/views/projects/tmpl/default.php ```

and change line ~179:
```php
 <?php echo JHtml::_('pfhtml.label.datetime', $item->start_date); ?>
```

Into this:
```php
 <?php echo date("d.m.Y", strtotime($item->start_date)); ?>
```

if you want the American date format, use 
```php
 <?php echo date("m.d.Y", strtotime($item->start_date)); ?>
```

You can also format the date however you want by referencing the PHP date() documentation [here](http://php.net/manual/en/function.date.php)


Alternatively
you can edit the static method inside ``` libraries/projectfork/html/label.php ``` called ***datetime***, although this requires a little bit more advanced knowledge of PHP and Joomla programming, but this will change the way all similar date-labels are displayed throughout all of ProjectFork, at least to my (limited) undestanding.

**Comment by scree23** [comment]
Hi HelgeSverre, I figure this out a few days back, but regarding your post - so I know how to change the data format. It is very usefull, because when I used :

<?php echo (($item->end_date == $this->nulldate) ? $txt_notset : JHtml::_('date', $item->end_date, $date_format)); ?>

Gives me just strnegth date format.

Thank you for your help.
