### ISSUE TITLE
Cannot de-select project in repository

### ISSUE THREAD

**Issue by fishmonkeyman** [projectfork/Projectfork#1656]
I’m re-experiencing an issue I had in January 2014.

When a project is de-selected in repository, it merely re-loads the same project. 

It is possible to scroll through the dropdown list to select a different project, but this very slow and unwieldy where there are a large number of projects. 

The original issue was solved at the time by installing a patch provided by @eaxs (original thread #618) but now this bug appears to have resurfaced.

This is making switching between many project repository directories very difficult and time consuming for my client, so any advice would be greatly appreciated.

![0a-click on repository menu link](https://cloud.githubusercontent.com/assets/3658622/9117235/d30ca01a-3c60-11e5-9a95-49412bb8be43.jpg)

![0b active project remains the same](https://cloud.githubusercontent.com/assets/3658622/9117236/d32713dc-3c60-11e5-9f9f-7afa49bc4961.jpg)

**Comment by eaxs** [comment]
Fixed in dev branch.
