### ISSUE TITLE
More than 20 Repository folders cannot be displayed in most browsers

### ISSUE THREAD

**Issue by kdwoell** [projectfork/Projectfork#1667]
Two users notified me today they cannot access folders in their respective repositories if the number of file folders exceeds the default display of 20 folders.
This behavior is being seen on all browsers and operating systems.

Joomla Version: 3.4.3 Stable
Projectfork Version: 4.3.1 Stable
PHP Version: 5.4.45

**Comment by eaxs** [comment]
Fixed earlier in the dev branch.
