### ISSUE TITLE
Issue with Non SEF URLs

### ISSUE THREAD

**Issue by Srinivas37** [projectfork/Projectfork#1669]
Dear All,

We are using Joomla 3.4.4 and Projectfork 4.3.2 Stable.
We have a problem with when we use "Non SEF URLs". It's working properly when we use "SEF URLs".

I will explain the scenario:
In Milestones page, we could see the number of Task Lists, Tasks and attachments. Once we click on Tasks, it should show only the tasks from that particular milestone. But it's listing all the tasks from the whole project.
This is the problem when we disable "Search Engine Friendly URLs" under Global Configuration.

Please find the screenshots for reference and let me know if you need any other information.

![screen_milestone](https://cloud.githubusercontent.com/assets/6056715/9992488/2e0d6370-6090-11e5-8265-b6dc703f4a10.png)

![screen_without_sef](https://cloud.githubusercontent.com/assets/6056715/9992492/3442f23c-6090-11e5-8d34-d788cfd9e550.png)

![screen_with_sef](https://cloud.githubusercontent.com/assets/6056715/9992494/3bd8fb40-6090-11e5-86c8-70251fd866f3.png)

Kindly Suggest as soon as possible.

Regards,
Srinivas

**Comment by Srinivas37** [comment]
We are waiting for your response...

Kindly suggest as soon as possible.

Regards,
Srinivas

**Comment by Srinivas37** [comment]
We are waiting for your response...

Kindly suggest as soon as possible.

Regards,
Srinivas

**Comment by Srinivas37** [comment]
We are waiting for your response...

Kindly suggest as soon as possible.

Regards,
Srinivas

**Comment by Srinivas37** [comment]
We are waiting for your response...

Kindly suggest as soon as possible.

Regards,
Srinivas

**Comment by Srinivas37** [comment]
Can any one help on this???

Regards,
Srinivas

**Comment by angek** [comment]
@Srinivas37 I've had a look and can confirm that this is indeed a bug. I'll look into it.

**Comment by Srinivas37** [comment]
Thank you. Please let me know the fix as soon as possible.

**Comment by Srinivas37** [comment]
Any Updates ?

Regards,
Srinivas

**Comment by Srinivas37** [comment]
Thank you @eaxs ... It's worked.

Regards,
Srinivas
