### ISSUE TITLE
Create new project - error

### ISSUE THREAD

**Issue by djanael** [projectfork/Projectfork#1671]
url: index.php?option=com_pfprojects&view=project&layout=edit

error: 0 SplFileInfo::__construct() expects parameter 1 to be string, array given

**Comment by angek** [comment]
@djanael what version of PF? what version of Joomla?
Just tested it with Joomla 3.4.4 and PF 4.3.2 and couldnt reproduce your error

**Comment by djanael** [comment]
Hello my dear,
Joomla 3.4.4 and PF 4.3.2, but resolve a problem, uninstall component jHackguard (Siteground creator) and use component SecurityCheck. Thank You!

**Comment by angek** [comment]
glad to hear it's been resolved.
