### ISSUE TITLE
Projectfork / Jomsocial   aplication.js in emerald theme

### ISSUE THREAD

**Issue by stephenhadden** [projectfork/Projectfork#1678]
HI
I am having an issue where jomsocial javascript/js is not working as it conflicts with application.js which is the hide toolbar script. Does anyone know how to get around this? If I take out application.js, then all the js works in Jomsocial, however that is not ideal as I like the toggle side bar. 

Has anyone had this issue and fixed it. I jave installed JCH optimize and also Jquery easy to see if that could fix it and it hasnt.
Thanks for taking a look.

Regards

Stephen

**Comment by eaxs** [comment]
I've released a patch for the issue just now.
