### ISSUE TITLE
Menu item or module with all archived projects

### ISSUE THREAD

**Issue by dmware** [projectfork/Projectfork#1685]
Is there a way to create a menu item that shows all the archived projects from the fron end. Or maybe just a module that I can later embed within an article?

Thanks

**Comment by angek** [comment]
not without coding something up

**Comment by dmware** [comment]
Hello angek and thanks for your answer. Can i send you a request of estimate?

**Comment by angek** [comment]
@dmware, of course you can. Let me know the precise functionality you would like and I'll give you a fixed price. email me at support@angekdesign.com.au

**Comment by dmware** [comment]
I am sorry for the delay but I had some problems at work. I will write you soon. Thanks.

**Comment by eaxs** [comment]
Feature added in 4.3.3.
Create or edit a project overview menu item and check out the layout options.

**Comment by dmware** [comment]
Awesome! Thanks a lot :)
