### ISSUE TITLE
Front End Template Issue

### ISSUE THREAD

**Issue by HamThorne** [projectfork/Projectfork#1690]
I have one template set for all ProjectFork menu items (Goggles) and it seems to work fine with the exception of when I select Create-New Project. It then reverts to the default template. All the other Create functions use the Goggles template.
![assignments](https://cloud.githubusercontent.com/assets/15892523/11216006/fe7156f4-8d16-11e5-9d41-7b1455be6ca6.jpg)
![dashboard-correct-template](https://cloud.githubusercontent.com/assets/15892523/11216007/fe79e38c-8d16-11e5-94b7-38b4ca5e93b6.jpg)
![create-new-project-wrong-template](https://cloud.githubusercontent.com/assets/15892523/11216005/fe6f94c2-8d16-11e5-993a-1d3bc5356fd5.jpg)

**Comment by eaxs** [comment]
It seems that you don't have a menu item that links to the projects overview. That's why it reverts back to the default template. 

In the Joomla Backend, go to: Menus > Projectfork > Add New Menu Item. Then choose Projects > Overview as the Menu type and save it. This should fix the issue.
