### ISSUE TITLE
edit print layout

### ISSUE THREAD

**Issue by kofaysi** [projectfork/Projectfork#1706]
Dear Support,
dear Users,

I'd like to add new columns [Start date, Task list] to layout=print, when printing tasks. How can I accomplish that, please?

**Comment by bokigto** [comment]
Edit this file: 
https://github.com/projectfork/Projectfork/blob/dev/source/components/com_pfprojects/site/views/projects/tmpl/print.php

**Comment by bokigto** [comment]
<div id="projectfork" class="category-list<?php echo $this->pageclass_sfx;?> view-milestones-print">
    <table class="table table-striped cat-items">
        <thead>
            <tr>
                <th><?php echo JText::_('JGLOBAL_TITLE'); ?></th>
                <th class="nowrap center" style="width: 10%"><?php echo JText::_('COM_PROJECTFORK_MILESTONES'); ?></th>
                <th class="nowrap center" style="width: 10%"><?php echo JText::_('COM_PROJECTFORK_TASKS'); ?></th>
                <th class="nowrap" style="width: 10%"><?php echo JText::_('COM_PROJECTFORK_FIELD_START_DATE_LABEL'); ?></th>
                <th class="nowrap" style="width: 10%"><?php echo JText::_('COM_PROJECTFORK_FIELD_DEADLINE_LABEL'); ?></th>
                <th class="nowrap" style="width: 10%">Completed</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach($this->items AS $i => $item) :
                ?>
                <tr>
                    <td><?php echo $this->escape($item->title);?></td>
                    <td class="center"><?php echo $this->escape($item->milestones);?></td>
                    <td class="center"><?php echo $this->escape($item->tasks);?></td>
                    <td>
                        <?php
                        if ($item->start_date != $nulldate) {
                            echo JHtml::_('date', $item->start_date, $date_format);
                        }
                        ?>
                    </td>
                    <td>
                        <?php
                        if ($item->end_date != $nulldate) {
                            echo JHtml::_('date', $item->end_date, $date_format);
                        }
                        ?>
                    </td>
                    <td><?php echo $item->progress; ?>%</td>
                </tr>
                <?php
            endforeach;
            ?>
        </tbody>
    </table>
</div>

**Comment by kofaysi** [comment]
Thank you bokigto!

For my needs, I edited the \com_pftasks\views\tasks\tmpl\print.php file. And commented the "Assigned" column out and replaced the labels and item for "Start date".

copied lines 57 to 61 from https://github.com/projectfork/Projectfork/blob/dev/source/components/com_pfprojects/site/views/projects/tmpl/print.php

Sources used: https://github.com/projectfork/Translations/blob/master/languages/cs-CZ/site/cs-CZ.com_projectfork.ini
