### ISSUE TITLE
number of projects

### ISSUE THREAD

**Issue by gridfree** [projectfork/Projectfork#1709]
is there a way to control the number of projects each ACG can make?
would like to have a few different groups, 
group_1 - 3 projects
group_2 - 5 projects 
etc?

**Comment by angek** [comment]
@gridfree, Projectfork, by default, does not offer this functionality. The most appropriate way to achieve this is through some custom dev work. A plugin could achieve this without having to hack core Projectfork files.

**Comment by angek** [comment]
Hi @gridfree refer #1725
