### ISSUE TITLE
Gantt Chart Module Missing All Settings Tabs (mod_pf_gantt_1.1.0.zip)

### ISSUE THREAD

**Issue by graphicsminded** [projectfork/Projectfork#1720]
I searched (recent) previous issues and did not find anything like this issue.

### Background: I have installed:

- Joomla version 3.4.8
- Project Fork Package `pkg_projectfork_4-3-3-zip`
- Project Fork User Activity Plugin `plguseractivityprojectfork1-1-2-zip`
- Project Fork User Activity Module `moduseractivitypfsite1-1-1-zip`
- Project Fork Gantt Chart Module `mod_pf_gantt_1-1-0-zip`
- Project Fork AppTheme Template

I've installed `mod_pf_gantt_1.1.0.zip` a few times (via the Upload Package File tab and the Install from URL tab) thinking it was a corrupt module install but when I browse to Extensions>Modules>Gantt Chart the settings Tabs are missing. 

### I've attached an image to show.
<img width="1280" alt="screen shot 2016-03-01 at 12 48 33 pm" src="https://cloud.githubusercontent.com/assets/13318185/13440106/b0b365da-dfad-11e5-8b82-d476006fef2f.png">

Any Ideas?

**Comment by gridfree** [comment]
in admin goto component/projectfork/options(top left corner)/integration, yes to the first field css and the rest auto, or to the setting for your set up,,,,,load jquery admin is what your looking for, to make tabs appear in backend....

**Comment by graphicsminded** [comment]
### [Solved] For those who encounter this issue:
Thank you for your answer. In Components>ProjectFork/Options/Integration I had: 

    Load jQuery - Admin: Yes

and switched it to:

    Load jQuery - Admin: Auto

and it worked. Not sure how this fixed the problem but I can now see them. Thank you for your suggestion.

**Comment by ebaselga** [comment]
Is Gantt Chart for free version or just for pro? I can not find the module in the free one

**Comment by graphicsminded** [comment]
I believe it's pro.

**Comment by angek** [comment]
Yes, its for pro.
