### ISSUE TITLE
Feature Request - Booking Calender

### ISSUE THREAD

**Issue by ashnic** [projectfork/Projectfork#1727]
Hi, Do you have a feature where our clients can see a booking calendar and they can see available times where they can book in for appointments with us?
The way i envisage is that there is a 'book in now' link button which takes them to a calendar showing available slots, they click the slot they want and then we thank them and also sending a confirmation email.
Thanks
Ashleigh

**Comment by angek** [comment]
Hey @ashnic Projectfork doesn't provide this functionality. I'm not even certain that Projectfork is the ideal extension for your requirements.

**Comment by ashnic** [comment]
Hi Angek, thank you!
