### ISSUE TITLE
fatal error on any PF menu item (on Create Task, Tasks (display),..)

### ISSUE THREAD

**Issue by kofaysi** [projectfork/Projectfork#1731]
Dear users,

I installed Joomla 3.5.0 over J3.4.8. In 2.4.8 the PF had been running well and healthy. After the update I get an error:
> Fatal error: Call to a member function setState() on a non-object in /home/svjsvetova523-1.cz/svjsvetova523-1.cz/modules/mod_related_items/helper.php on line 44

How can I get my broken PF live again, please?

**Comment by kofaysi** [comment]
It seems I could solve it: For the Related Articles module, I set the Menu Assignment > Module Assignment to "only on the pages selected" and deselected the PF branch. The PF menu works as expected and displays the items.

**Comment by angek** [comment]
glad you got this solved.
