### ISSUE TITLE
Customer view for ProjectFork...

### ISSUE THREAD

**Issue by davebarrettdesigns** [projectfork/Projectfork#1733]
Hi - before I move on and buy ProjectFork I wondered if there was a way to give customers a top-line "information only" screen and have the Dashboard accessed centrally by an administrator... 

I will give you an example:
I want to have a central control panel where I can update all the different milestones and "current status" information for multiple clients but i only want the relevant client to see certain information via a microsite:

SO, if I have 10 clients all having multiple new properties painted and carpeted I can manage all their projects and update their progress centrally but all I want the client to see is, for example:

Client one's microsite, branded and sitting behind a login...
There will be a series of fields with drop downs beneath 

Field one: 
Venue...
Drop downs from this field for selection: 
1. 1 High Street
2. 15 Acacia Avenue
3. 28 New Road

Field Two:
Activity...
Drop downs from this field for selection: 
1. Walls painted
2. Ceilings painted
3. Carpets laid

Field Three (relative to the "Activity" and "Venue" chosen:
Current Status
1. Due 05.05.16 (will vary)
2. Completed

IS this something ProjectFork can do?
Many thanks
David

**Comment by angek** [comment]
it sounds feasible but you need to try it out first by installing the free version of Projectfork and having a play.
I believe if you set up your Joomla groups and acl correctly, then set up each one of the properties ( 1 high street, 15 acacia avenue) as projects and the activities as project tasks you should be able to achieve what you are trying to accomplish. Additionally you may need to customise some of Projectfork's views but that shouldnt be too difficult with a little programming knowledge.
