### ISSUE TITLE
email notification

### ISSUE THREAD

**Issue by bradsayers** [projectfork/Projectfork#331]
Just download ver 4 and began setting up projects and assigning the appropriate groups.

However, my users are not getting notified by email.

I then searched the forum and saw that kyleledbetter commented 4 months ago "We're adding email notifications now for Beta. The share icons could easily be done in a template, plugin or extension, don't need to be in the core of Projectfork. Once we're stable I'm sure the translations will come pouring in."

Just wondered if this option is not yet available, or if I am missing something.

Using:
    Joomla Version: 2.5.8 Stable
    Projectfork Version: 4.0.0 Stable
    PHP Version: 5.2.42

Thanks, Brad

**Comment by eaxs** [comment]
Feature added.
