### ISSUE TITLE
No more features please!

### ISSUE THREAD

**Issue by EdgyLedgyWedgbarge** [projectfork/Projectfork#889]
I've just upgraded to Projectfork Pro because I really needed the Gantt chart features for my projects.
So I'm now entitled to vote for new features!
Please - no new features!
Please - sort and and improve the features we already have.

I was expecting a lot more from the Gantt charts:
- I presumed I'd be able to move the bars around on the chart to set the dates, not have to go into each item and set the dates trying to remember what dates all the other items start and finish. Or trying to change an item date and realising it falls out of the bounds of the parent milestone so having to go back edit that first. I don't find it all that useable at all.
- I had the problem with all the tasks disappearing on mouseOver. I tried setting "Load Bootstrap CSS" to No - that made it worse! I tried setting "Load Bootstrap JS" to No and that seemed to fix it. However, with this set, I can no longer see any details of the designs - When I click the "Details" dropdown button in Designs view nothing happens (but the details does appear if I have "Load Bootstrap JS" set to Yes). 

- I was hoping some of the alignment of elements within the whole interface would have been improved by now.

Sorry to seem a bit of a moan but as I said I after paying for the Pro version, I was hoping for a bit more. I would hate to see the next version with "Great new features e.g. Invoicing" with all the other features left in a half-hearted, incomplete state.

**Comment by LegendsWeb** [comment]
I have a new install of ProjectFork ... I have the problem of titles disappearing on mouseOver on the Gantt chart.  Using Joomla 2.5, Emerald theme.  Is there a thread that resolves this??
